### ISSUE TITLE
One-week format

### ISSUE THREAD

**Issue by martinduke** [mirjak/draft-shmoo-online-meeting#10]
At IETF 111 there was considerable (but not unanimous) sentiment for a longer format (more than 1 week) to reduce the number of
conflicts, and the intensity of IETF week.

This issue is a thread to allow further discussion.

**Comment by martinduke** [comment]
Personally, I think a spread-out format is a mistake. It becomes substantially harder to block a period of time for IETF. To the extent that the meeting disperses into a bunch of interims, those will all individually optimize for their participants and you will end up with almost all meetings optimized for Atlantic time.

**Comment by mirjak** [comment]
As earlier survey indicated that people don't want to extend for more then one week, the draft currently says

```
If the number of requested sessions exceeds the number of possible slots with the usual 8 parallel tracks, it is possible for an online-only meeting to use more tracks. After all, this decision is implicitly made by the working group chairs requesting a certain number of sessions and length. While realistic planning is desired to avoid running over time, chairs are still encouraged to request plenary meeting time carefully and use interims where possible and sensible instead.
```

I personally agree with Martin that I think there is value in having one and only one condensed week with cross interactions and therefore I think it's more in the hands of the chairs to solve the conflict problem as indicated by this text. However, I'd wish we had that much less session requests, so that we could even go for less than 5 days or, even better, less than 6 hours a day. Chairs, please actively choose the right format for each kind of meeting, rather than use the default option. Not having the time restriction by travel provides a lot of flexibility that we don't use well yet. But there is still value in some kind of plenary meeting I think.

**Comment by mirjak** [comment]
I created PR #12
